name: Super Linter

on:
  push:
    branches:
      - workflows
  pull_request:
    branches:
      - workflows

jobs:
  super-linter:
    name: Lint code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Super Linter
        uses: github/super-linter@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit: ${{ github.sha }}
          validate-yaml: false
