name: Test and lint

on:
  push:
    branches:
      - workflows
  pull_request:
    branches:
      - workflows

jobs:
  test-and-lint:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Install the latest stable Go version
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: stable

      # Install golint
      - name: Install golint
        run: |
          go get -u golang.org/x/lint/golint

      # Install any dependencies needed for testing
      - name: Install Dependencies
        run: go mod download 

      # Run tests
      - name: Run Tests
        run: go test ./...

      # Run linting
      - name: Run Linting
        run: golint ./...
