name: Test and Lint

on:
  push:
    branches:
      - workflows
  pull_request:
    branches:
      - workflows

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install any dependencies needed for testing and linting
      - name: Install Dependencies
        run: |
          go mod download 

      # Run tests
      - name: Run Tests
        run: |
          go test ./...

      # Run linting (assuming you have a linter configured for your project)
      - name: Run Linting
        run: |
          golangci-lint run
