name: Test and Lint

on:
  push:
    branches:
      - workflows
  pull_request:
    branches:
      - workflows

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install stable Go version
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      # Install any dependencies needed for testing
      - name: Install Dependencies
        run: go mod download 

      # Add Super Linter action
      - name: Super Linter
        uses: github/super-linter@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit: ${{ github.sha }}
          validate-yaml: false

      # Run tests
      - name: Run Tests
        run: go test ./...
