name: Test and Lint

on:
  push:
    branches:
      - workflows
  pull_request:
    branches:
      - workflows

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install any dependencies needed for testing
      - name: Install Dependencies
        run: go mod download 

      # Install golangci-lint using Go
      - name: Install golangci-lint
        run: go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.42.1

      # Run tests
      - name: Run Tests
        run: go test ./...

      # Run linting with golangci-lint
      - name: Run Linting
        run: golangci-lint run
